import Nav from "./components/Nav";import Hero from "./components/Hero";import ProjectCard from "./components/ProjectCard";import DigitalTwin from "./components/DigitalTwin";
const projects=[
{number:"01",title:"Incremental / Rip Routing",description:"Routing infrastructure focused on localized DRC fixing, incremental routing and runtime reduction.",meta:"EDA / ROUTING\nSYSTEMS / C++",tags:["Routing","Algorithms","EDA","Performance"]},
{number:"02",title:"DRC Fixing Infrastructure",description:"Automated DRC-fixing infrastructure with targeted violation processing and runtime-oriented improvements.",meta:"EDA / DRC\nENGINEERING",tags:["DRC","Optimization","Automation"]},
{number:"03",title:"Temporal Knowledge Graphs",description:"Research into forecasting and reasoning over temporal knowledge graphs.",meta:"ML / RESEARCH\nKNOWLEDGE GRAPHS",tags:["PyTorch","KG","Temporal ML"]},
{number:"04",title:"LLM + Knowledge Graph QA",description:"Benchmarking and experimentation with knowledge-graph-induced LLM reasoning systems.",meta:"LLM / NLP\nRESEARCH",tags:["LLMs","NLP","Reasoning"]}];
export default function Home(){return <><Nav/><main><Hero/>
<section className="section" id="work"><div className="container"><div className="section-head"><div><div className="section-number">01 / SELECTED WORK</div><h2>Things I<br/>build.</h2></div><p className="section-intro">Engineering and research projects, presented as technical case studies rather than a conventional resume.</p></div><div className="projects">{projects.map(p=><ProjectCard key={p.number} project={p}/>)}</div></div></section>
<section className="section" id="about"><div className="container two-col"><div><div className="section-number">02 / ABOUT</div><p className="big-text">AI, algorithms and systems — with a bias toward understanding how things work.</p></div><div className="muted"><p>TODO: Add your final biography in <code>content/about/profile.md</code>.</p><p>This portfolio is designed to show the problems you solve, the systems you build and the thinking behind them.</p></div></div></section>
<section className="section" id="research"><div className="container two-col"><div><div className="section-number">03 / RESEARCH</div><h2>Research<br/>& ideas.</h2></div><div className="muted"><p>TODO: Add publications, thesis, talks and research timeline.</p><p>Current themes: temporal knowledge graphs, LLM reasoning, knowledge-graph-induced QA and intelligent systems.</p></div></div></section>
<section className="section" id="experience"><div className="container two-col"><div><div className="section-number">04 / EXPERIENCE</div><h2>Where I’ve<br/>worked.</h2></div><div className="timeline"><div className="timeline-item"><div className="date">CURRENT / TODO</div><h3>Current Role</h3><p className="muted">TODO: Add current role.</p></div><div className="timeline-item"><div className="date">2023</div><h3>IBM — Routing Team</h3><p className="muted">TODO: Add public-safe details and quantified impact.</p></div><div className="timeline-item"><div className="date">2022</div><h3>Samsung Research</h3><p className="muted">TODO: Add public-safe details and quantified impact.</p></div></div></div></section>
<section className="section" id="skills"><div className="container"><div className="section-number">05 / SKILLS</div><h2>Tools of<br/>the trade.</h2><div className="skills">{["Python","C++","PyTorch","LLMs","Transformers","Knowledge Graphs","Algorithms","EDA","Routing","Linux","Git"].map(s=><span className="skill" key={s}>{s}</span>)}</div></div></section>
<section className="section" id="twin"><div className="container"><div className="section-head"><div><div className="section-number">06 / DIGITAL TWIN</div><h2>Talk to<br/><em>Jayant AI.</em></h2></div><p className="section-intro">Ask questions about Jayant’s work, research, education and technical interests.</p></div><DigitalTwin/></div></section>
</main><footer className="footer"><div className="container">© 2026 Jayant Singh · Interactive technical portfolio.</div></footer></>}